# Get base SDK Image from Microsoft
From mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
WORKDIR /app

#Copy the CSPROJ file and restore any dependencies (via Nuget)
COPY *.csproj ./
RUN dotnet restore

#Copy the project files and build our release 
COPY . ./
RUN dotnet publish -c Release -o out


#Generate runtime image
From mcr.microsfot.com/dotnet/core/aspnet:2.2
WORKDIR /app
EXPOSE 80
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "DockerAPI.dll"]